apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway
spec:
  rules:
    - host: your-domain.com # Need to add the domain here !!
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: controller-service
                port:
                  number: 80
