version: '3.8'

services:
  # LLM API Service
  llm_api:
    build:
      context: ./Services/AI
      dockerfile: Dockerfile
    ports:
      - "9191:9191"
    container_name: llm_api
    restart: unless-stopped

  # PDF Extraction Service
  extract_pdf:
    build:
      context: ./Services/PdfExtractor
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    container_name: extract_pdf
    restart: unless-stopped

  # Main Controller Service
  main_controller:
    build:
      context: ./App
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    container_name: app
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}  # Uses value from .env file
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    entrypoint: ["./wait-for-it.sh", "database", "5432", "--", "python", "app.py"]
    restart: unless-stopped

  # PostgreSQL Database
  db:
    build:
      context: ./Services/Database
      dockerfile: Dockerfile.db
    container_name: database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Nginx Reverse Proxy for all services
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - llm_api
      - extract_pdf
      - main_controller
    volumes:
      - ./docs:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

# Persistent volume for PostgreSQL data
volumes:
  db_data:
