version: '3.8'

services:
  # LLM API Service
  llm_api:
    build:
      context: ./Services/AI  # Directory containing Dockerfile and LLM_API.jar
      dockerfile: Dockerfile
    ports:
      - "9191:9191"
    container_name: llm_api
    restart: unless-stopped
    networks:
      - app_network

  # PDF Extraction Service
  extract_pdf:
    build:
      context: ./Services/PdfExtractor  # Directory containing Dockerfile and ExtractPdf.py
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    container_name: extract_pdf
    restart: unless-stopped
    networks:
      - app_network

  # Main Controller Service
  main_controller:
    build:
      context: ./App  # Directory containing Dockerfile and app.py
      dockerfile: Dockerfile.app
    ports:
      - "5002:5002"
    container_name: app
    restart: unless-stopped
    networks:
      - app_network
    environment:
      DB_HOST: db  # Hostname of the PostgreSQL service
      DB_PORT: 5432
      DB_NAME: Lernassistent
      DB_USER: postgres
      DB_PASSWORD: postgres

  # PostgreSQL Database
  db:
    build:
      context: ./Services/Database   # Directory containing Dockerfile and app.py
      dockerfile: Dockerfile
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Lernassistent
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app_network

  # Nginx Reverse Proxy for all services
  nginx:
    build:
      context: .  # Directory containing Dockerfile.nginx
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"    # HTTP
    #   - "443:443"  # HTTPS (commented out)
    depends_on:
      - llm_api
      - extract_pdf
      - main_controller
      - db  # Uncomment if nginx interacts with the database
    volumes:
      - ./docs:/usr/share/nginx/html:ro  # Mount the docs directory to Nginx web root
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Custom Nginx config
    restart: unless-stopped
    networks:
      - app_network

# Persistent volume for PostgreSQL data
volumes:
  db_data:

# Shared network for inter-service communication
networks:
  app_network:
