version: '3.8'

services:
  # LLM API Service
  llm_api:
    build:
      context: ./Services/AI  # Directory containing Dockerfile and LLM_API.jar
      dockerfile: Dockerfile
    ports:
      - "9191:9191"
    container_name: llm_api
    restart: unless-stopped

  # PDF Extraction Service
  extract_pdf:
    build:
      context: ./Services/PdfExtractor  # Directory containing Dockerfile and ExtractPdf.py
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    container_name: extract_pdf
    restart: unless-stopped

  # Main Controller Service
  main_controller:
    build:
      context: ./App  # Directory containing Dockerfile and MainController.py
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    container_name: main_controller
    restart: unless-stopped

  # PostgreSQL Database
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Lernassistent
    ports:
      - "5433:5433"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Nginx Reverse Proxy for all services
  nginx:
    build:
      context: .  # Directory containing Dockerfile.nginx
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"    # HTTP
    #   - "443:443"  # HTTPS (commented out)
    depends_on:
      - llm_api
      - extract_pdf
      - main_controller
      # Uncomment below when you decide to use the db-dependent app
      # - app_with_db
    volumes:
      - ./docs:/usr/share/nginx/html:ro  # Mount the docs directory to Nginx web root
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Custom Nginx config
    restart: unless-stopped

# Persistent volume for PostgreSQL data
volumes:
  db_data: