version: "3.8"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db  # Reference the custom database Dockerfile
    environment:
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: main_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.app  # Reference your app Dockerfile
    depends_on:
      - db
    environment:
      - DB_URL=postgres://db_admin:password123@db:5432/main_db
      - DB_USER=db_admin
      - DB_PASSWORD=password123
      - DB_NAME=main_db
    ports:
      - "8000:8000"  # Assuming your app listens on port 8000

volumes:
  postgres_data:
