version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdbname
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      - DB_URL=db
      - DB_USER=yourusername
      - DB_PASSWORD=yourpassword
      - DB_NAME=yourdbname
    ports:
      - "5000:5000"

volumes:
  postgres_data:
