version: '3.8'

services:
  llm_api:
    build:
      context: ./Services/AI  # Directory containing Dockerfile and LLM_API.jar
      dockerfile: Dockerfile
    ports:
      - "9191:9191"
    container_name: llm_api
    restart: unless-stopped

  extract_pdf:
    build:
      context: ./Services/PdfExtractor # Directory containing Dockerfile and ExtractPdf.py
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    container_name: extract_pdf
    restart: unless-stopped

  main_controller:
    build:
      context: ./App  # Directory containing Dockerfile and MainController.py
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    container_name: main_controller
    restart: unless-stopped
