version: '3.8'
services:
  php-controller:
    build: ./php-controller
    networks:
      - microservices-net
    ports:
      - "8000:8000"

  python-service:
    build: ./python-service
    networks:
      - microservices-net

  node-service:
    build: ./node-service
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
