version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: magna
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: ai_project_db  # Ensure this matches the database you want
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data:
